/** @type {import('tailwindcss').Config} */
module.exports = {
    content: [
        './app/**/*.{js,jsx,ts,tsx}',
        './components/**/*.{js,jsx,ts,tsx}',
    ],
    presets: [require('nativewind/preset')],
    theme: {
        extend: {
            colors: {
                canvas: '#FDFDFD',
                ink: '#0F0F0F',
                primary: {
                    DEFAULT: '#0F3826',
                    dark: '#0A2419',
                    light: '#E8F5EE',
                },
                secondary: '#16A34A',
                violet: {
                    DEFAULT: '#7C3AED',
                    light: '#F3EEFF',
                    dark: '#5B21B6',
                },
                accent: {
                    DEFAULT: '#92400E',
                    light: '#FEF3C7',
                    dark: '#78350F',
                },
                background: '#F8F7F5',
                surface: '#FFFFFF',
                muted: '#9CA3AF',
                success: '#16A34A',
                error: '#DC2626',
                info: '#2563EB',
                warning: '#D97706',
                'text-primary': '#1A1A1A',
                'text-secondary': '#6B7280',
                'card-border': 'rgba(0,0,0,0.06)',
                divider: 'rgba(0,0,0,0.04)',
                gray: {
                    100: '#F3F4F6',
                    200: '#E5E7EB',
                    300: '#D1D5DB',
                    400: '#9CA3AF',
                    500: '#6B7280',
                },
                glass: 'rgba(255,255,255,0.72)',
                'glass-dark': 'rgba(15,56,38,0.80)',
                'glass-light': 'rgba(253,253,253,0.85)',
                'success-light': '#DCFCE7',
                'error-light': '#FEE2E2',
                'warning-light': '#FEF3C7',
                'info-light': '#DBEAFE',
                'violet-glow': 'rgba(124, 58, 237, 0.15)',
            },
            fontFamily: {
                sans: ['Inter-Regular', 'System'],
                jakarta: ['PlusJakartaSans-Regular'],
                'jakarta-semibold': ['PlusJakartaSans-SemiBold'],
                'jakarta-bold': ['PlusJakartaSans-Bold'],
                'jakarta-xbold': ['PlusJakartaSans-ExtraBold'],
                inter: ['Inter-Regular'],
                'inter-medium': ['Inter-Medium'],
                'inter-semibold': ['Inter-SemiBold'],
                'inter-bold': ['Inter-Bold'],
            },
            borderRadius: {
                xs: '6px',
                sm: '10px',
                md: '14px',
                lg: '20px',
                xl: '28px',
                '2xl': '36px',
            },
            spacing: {
                '4.5': '18px',
                '13': '52px',
                '15': '60px',
                '18': '72px',
            },
            fontSize: {
                'display': ['40px', { lineHeight: '46px', letterSpacing: '-0.8px' }],
                'h1': ['30px', { lineHeight: '36px', letterSpacing: '-0.6px' }],
                'h2': ['22px', { lineHeight: '28px', letterSpacing: '-0.4px' }],
                'h3': ['17px', { lineHeight: '24px', letterSpacing: '-0.2px' }],
                'body-lg': ['17px', { lineHeight: '26px' }],
                'body': ['15px', { lineHeight: '22px' }],
                'body-sm': ['13px', { lineHeight: '18px' }],
                'label': ['11px', { lineHeight: '14px', letterSpacing: '0.8px' }],
                'label-sm': ['9px', { lineHeight: '12px', letterSpacing: '1.2px' }],
                'data': ['28px', { lineHeight: '34px', letterSpacing: '-0.5px' }],
                'data-sm': ['18px', { lineHeight: '24px' }],
            },
        },
    },
    plugins: [],
};
